### ISSUE TITLE
App is crashing whenever the webview is opened to connect a platform

### ISSUE THREAD

**Issue by WaheedHussainHaans** [getphyllo/phyllo-connect-flutter#33]
### flutter doctor -v output
`[✓] Flutter (Channel stable, 3.13.0, on macOS 13.0 22A380 darwin-arm64, locale en-GB)
    • Flutter version 3.13.0 on channel stable at /Users/waheed/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (5 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/waheed/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • 2201116TG (mobile) • BQINFAUGH6KZXCN7 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!`

**Here** are the logs

`W/techsaints.solo(16124): Attempt to remove non-JNI local reference
E/AndroidRuntime(16124): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(16124): Process: com.techsaints.solo, PID: 16124
E/AndroidRuntime(16124): java.io.IOException: unexpected end of stream on Connection{geolocation-db.com:443, proxy=DIRECT hostAddress=geolocation-db.com/159.89.102.253:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
E/AndroidRuntime(16124): 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(16124): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(16124): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(16124): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(16124): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
E/AndroidRuntime(16124): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
E/AndroidRuntime(16124): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(16124): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(16124): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(16124): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(16124): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d73345a, Dispatchers.Default]
E/AndroidRuntime(16124): Caused by: java.io.EOFException: \n not found: limit=0 content=…
E/AndroidRuntime(16124): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:236)
E/AndroidRuntime(16124): 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
E/AndroidRuntime(16124): 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
E/AndroidRuntime(16124): 	... 19 more
W/DefaultDispatch(16124): type=1400 audit(0.0:568607): avc: denied { search } for name="miuilog" dev="dm-40" ino=1132179 scontext=u:r:untrusted_app:s0:c130,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.techsaints.solo
W/OOMEventManagerFK(16124): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
I/Process (16124): Process is going to kill itself!
I/Process (16124): java.lang.Exception
I/Process (16124): 	at android.os.Process.killProcess(Process.java:1330)
I/Process (16124): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:202)
I/Process (16124): 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle.aab-stable-584517231:17)
I/Process (16124): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process (16124): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process (16124): 	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:61)
I/Process (16124): 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
I/Process (16124): 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:196)
I/Process (16124): 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
I/Process (16124): 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
I/Process (16124): 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
I/Process (16124): 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
I/Process (16124): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
I/Process (16124): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
I/Process (16124): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
I/Process (16124): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
I/Process (16124): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
I/Process (16124): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
I/Process (16124): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
I/Process (16124): Sending signal. PID: 16124 SIG: 9
Lost connection to device.`

**Comment by bhanubbs** [comment]
Do update to the latest version,  clean pods or cache repair, That fixes the problem
